### ISSUE TITLE
[FEATURE] Use loaded SVG files in the footer

### ISSUE THREAD

**Issue by Panquesito7** [web3community/devprotocol.xyz#106]
### Detailed description

Instead of using in-HTML SVGs, I think we should load the SVGs from a file using the `img` tag (this for example can be seen in the footer file).

https://github.com/web3community/devprotocol.xyz/blob/cd851e4900c16e366435ce7203e71ae59333de3f/src/components/Global/Footer.astro#L24-L36

This can also be seen in other parts of the code in that file.

### Context

It would make the code shorter and easier to read, IMO.

### Possible implementation

Use loaded SVGs using the `img` tag in the footer file.

### Additional information

Nope.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kunal0007** [comment]
Can I work on this issue?

**Comment by krishguptadev** [comment]
Sure 😄

**Comment by Kunal0007** [comment]
Thanks
