### ISSUE TITLE
[FEATURE] Replace the design in DEV Token section

### ISSUE THREAD

**Issue by shuklaritvik06** [web3community/devprotocol.xyz#110]
### Current
![ss](https://user-images.githubusercontent.com/72812470/140695938-8ba7143d-38dd-4f83-8e75-4c00ecdaf03e.png)
### Wanted
![Wanted](https://user-images.githubusercontent.com/72812470/140695958-c314cd3e-ee27-45e4-bc3b-dfd759b88732.png)

### Context

You can see the design here - https://www.figma.com/file/rmCKKIsjSWCH0q6lObDQC8/Dev-Protocol-design?node-id=0%3A1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhinavMV** [comment]
I would like to work this.
But before that may i know How should this look in smaller view(Mobile and tablet)?

**Comment by vinzvinci** [comment]
> I would like to work on this. But before that may i know How should this look in smaller view(Mobile and tablet)?

CC @krishguptadev

**Comment by krishguptadev** [comment]
> I would like to work on this. But before that may i know How should this look in smaller view(Mobile and tablet)?

it should look exactly like the current design on desktop...

**Comment by AbhinavMV** [comment]
I have changed it look like figma design in desktop view.
![image](https://user-images.githubusercontent.com/35369843/141638640-b82b8fde-6d52-4ee3-85be-f083cf60f0da.png)

But this is how it is in mobile view. 
Could we connect over discord to get a better understanding for mobile view?
discord id - Blank07#8280
![image](https://user-images.githubusercontent.com/35369843/141639259-5885fe6b-a1c8-40ba-b858-87245437e9ad.png)

**Comment by krishguptadev** [comment]
> I have changed it look like figma design in desktop view. ![image](https://user-images.githubusercontent.com/35369843/141638640-b82b8fde-6d52-4ee3-85be-f083cf60f0da.png)
> 
> But this is how it is in mobile view. Could we connect over discord to get a better understanding for mobile view? discord id - Blank07#8280 ![image](https://user-images.githubusercontent.com/35369843/141639259-5885fe6b-a1c8-40ba-b858-87245437e9ad.png)

but every thing ain't centered on mobile 🤔

**Comment by AbhinavMV** [comment]
Centered everything for mobile view. If this is ok can i create a PR ?

![image](https://user-images.githubusercontent.com/35369843/141645321-d8a2d6b2-0652-48a7-9f58-f57ff546e3e3.png)

**Comment by vinzvinci** [comment]
> Centered everything for mobile view. If this is ok can i create a PR ?
> 
> ![image](https://user-images.githubusercontent.com/35369843/141645321-d8a2d6b2-0652-48a7-9f58-f57ff546e3e3.png)

yeah looks good

**Comment by shuklaritvik06** [comment]
> Centered everything for mobile view. If this is ok can i create a PR ?
> 
> ![image](https://user-images.githubusercontent.com/35369843/141645321-d8a2d6b2-0652-48a7-9f58-f57ff546e3e3.png)

LGTM ✨
