### ISSUE TITLE
[BUG] navbar and footer bug in mobile view

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#123]
### Description

![image](https://user-images.githubusercontent.com/73097560/141035542-72899b8e-4002-4925-b36f-8d5d5ae5545d.png)

![image](https://user-images.githubusercontent.com/73097560/141035551-b871b18f-8b80-4049-9874-780afc905881.png)

### Expected behavior

I provided info. on what to change, please see the image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Can u also help fix this @krishguptadev?

**Comment by krishguptadev** [comment]
> Can u also help fix this @krishguptadev?

not sure about the nav (since I didn't yet see how it works), but can fix the image. I believe it is some unnessarcy margin

**Comment by vinzvinci** [comment]
I'll make new navbar in figma

**Comment by krishguptadev** [comment]
The alignment is fixed right?

**Comment by vinzvinci** [comment]
Yes @krishguptadev, I'll change the title

**Comment by AbhinavMV** [comment]
Hello i think this issue is fixed now. Navbar and footer issue was because of the image.
Please find below the screenshot.
Let me know if you can still replicate the issue. I would like to fix it. 😄
![image](https://user-images.githubusercontent.com/35369843/141522344-7b1a8b08-ec43-405b-8cbf-cbbc04209b0f.png)

**Comment by vinzvinci** [comment]
Yeah, can u fix it @AbhinavMV? 

the image size from that 3 pages should be the same.

**Comment by Panquesito7** [comment]
> Hello i think this issue is fixed now. Navbar and footer issue was because of the image. Please find below the screenshot. Let me know if you can still replicate the issue. I would like to fix it. 😄 ![image](https://user-images.githubusercontent.com/35369843/141522344-7b1a8b08-ec43-405b-8cbf-cbbc04209b0f.png)

Glad to see you fixed it! Could you please create a PR, follow the instructions [**here**](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md), and make a PR. 🙂

**Comment by AbhinavMV** [comment]
Reason for issue - image size improper 
Fix already done and merged in #125 
Please check again and let me know if issue is still there

**Comment by AbhinavMV** [comment]
Reason for issue - image size improper 
Fix already done and merged in #125 
Please check again and let me know if issue is still there.

**Comment by vinzvinci** [comment]
I was thinking that I give the wrong size of the image. This issue isn't fixed yet

**Comment by AbhinavMV** [comment]
Yes my mistake was looking for the bug in main page instead of creators/patrons page
Have fixed the bug and raised a PR #136 
Let me know if there is any problems in it. 
Thankyou
