### ISSUE TITLE
[BUG] Wrong Stakes.Social link for Vyper

### ISSUE THREAD

**Issue by Panquesito7** [web3community/devprotocol.xyz#127]
### Description

The link to Vyper's Stakes.Social profile is wrong. It leads you to Chalk's profile.

### Expected behavior/contents

Link to Vyper's Stakes.Social profile.

### Actual behavior/contents

The current link leads to Chalk.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
https://stakes.social/0x90168f9Ba07B95f629f8b77F789d46A549d6470F - here's the link for vyper
