### ISSUE TITLE
[FEATURE] Replace the dapps design to cards slider 

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#131]
### Detailed description

We should change the dapps section design

### Current

![image](https://user-images.githubusercontent.com/73097560/141305138-282f087e-94dc-4506-a52f-33045db40e2d.png)

### Context

We think this feature is good 
https://tailwindui.com/components/application-ui/lists/grid-lists#component-5d72b187beb968e12db89fe49f272b18

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Would u like to continue this issue and create PR @MatteuSan?

**Comment by AbhinavMV** [comment]
Should this section look kind of like creator success stories? 
![image](https://user-images.githubusercontent.com/35369843/141829354-1c18f0ca-3adb-4f5f-9f6d-c99473ea1ff7.png)

Or should this be like 4 cards ?
![image](https://user-images.githubusercontent.com/35369843/141829464-ab81061d-29a4-412a-b92f-73e678533cee.png)

**Comment by MatteuSan** [comment]
@vinzvinci i won’t be working on this for the current version of the website. I suppose once the design system is out I’ll be able to

**Comment by vinzvinci** [comment]
> Should this section look kind of like creator success stories?
Image above

Nope
> 
> Or should this be like 4 cards? 
Image above

Yeah

**Comment by vinzvinci** [comment]
> @vinzvinci i won’t be working on this for the current version of the website. I suppose once the design system is out I’ll be able to

Hmm. I'm not sure if aggre wants it, but let's wait for his chat on discord

**Comment by ZaidKhan2002** [comment]
@vinzvinci can you check this https://kitwind.io/products/kometa/components it has some better options rather than above cards.

**Comment by vinzvinci** [comment]
https://kitwind.io/products/kometa/components/features I like this, but is this open source?

**Comment by AbhinavMV** [comment]
> https://kitwind.io/products/kometa/components/features I like this, but is this open source?
> 
> ![image](https://user-images.githubusercontent.com/73097560/142406053-8749f460-f637-4a16-bf93-25a8b8cd92dd.png)

this can be achieved just using tailwind right ?

**Comment by vinzvinci** [comment]
> > https://kitwind.io/products/kometa/components/features I like this, but is this open source?
> > ![image](https://user-images.githubusercontent.com/73097560/142406053-8749f460-f637-4a16-bf93-25a8b8cd92dd.png)
> 
> this can be achieved just using tailwind right ?

yeah

**Comment by vinzvinci** [comment]
If u find something here, that'll be useful https://tailwindui.com/

**Comment by AbhinavMV** [comment]
with tailwind we would be able to make most of card design.
but i was thinking there might be more dapps added in the future right so this section would keep on increasing.
so how about we make this section into a card carousel?

**Comment by shuklaritvik06** [comment]
> with tailwind we would be able to make most of card design. but i was thinking there might be more dapps added in the future right so this section would keep on increasing. so how about we make this section into a card carousel?

Yep I think this will look good

**Comment by ZaidKhan2002** [comment]
> with tailwind we would be able to make most of card design. but i was thinking there might be more dapps added in the future right so this section would keep on increasing. so how about we make this section into a card carousel?

Yes we can go with that.

**Comment by vinzvinci** [comment]
Okay cool, can u start that @ZaidKhan2002 ?

**Comment by ZaidKhan2002** [comment]
@AbhinavMV would you like to work upon this or should I start

**Comment by AbhinavMV** [comment]
You can start @ZaidKhan2002

**Comment by ZaidKhan2002** [comment]
Sure!!

**Comment by ZaidKhan2002** [comment]
I made 3 cards and inserted all the details but I am unable to make slider/carousel as it will be in vue and I am not familiar with it. My apologies.

**Comment by ZaidKhan2002** [comment]
> https://kitwind.io/products/kometa/components/features I like this, but is this open source?
> 
> ![image](https://user-images.githubusercontent.com/73097560/142406053-8749f460-f637-4a16-bf93-25a8b8cd92dd.png)

Also I did try this also.

**Comment by vinzvinci** [comment]
Our final decision is to add a card carousel @ZaidKhan2002 and not the kometa. Can u still take this issue?

**Comment by krishguptadev** [comment]
> I made 3 cards and inserted all the details but I am unable to make slider/carousel as it will be in vue and I am not familiar with it. My apologies.

np, just make the cards... I can try implementing the slider feature 🙂

**Comment by AbhinavMV** [comment]
Maybe we can use this package? -> vue3-carousel
https://github.com/ismail9k/vue3-carousel

**Comment by krishguptadev** [comment]
> Maybe we can use this package? -> vue3-carousel https://github.com/ismail9k/vue3-carousel

@ZaidKhan2002 can you see this once? 🤔

**Comment by ZaidKhan2002** [comment]
@vinzvinci I am unable to do this. Can you assign this to someone.

**Comment by AbhinavMV** [comment]
@krishguptadev if you are not working on this then i would like to 😄

**Comment by krishguptadev** [comment]
> @krishguptadev if you are not working on this then i would like to 😄

I was thinking to work but sure! All over to you!

**Comment by AbhinavMV** [comment]
> > @krishguptadev if you are not working on this then i would like to 😄
> 
> I was thinking to work but sure! All over to you!

Thankyou 😄
