### ISSUE TITLE
[FEATURE] Change the navbar items 

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#134]
### Detailed description

OVERVIEW | DAO | Community | Help | Launch App

**Overview**
| For Creators
| For Patrons
| For Developers
| [Roadmap](https://trello.com/b/oFu5uWJF/roadmap)

**DAO**
| [Voting Portal](https://govern.devprotocol.xyz/)

**Community**
| Forum
| Builders Program

**Help**
| FAQ
| Tutorials
| Documentation
| Code of Conduct

**Launch App** = Button for [Stakes.social](http://stakes.social/)

### Context

Dev Protocol team decided to change the navbar items with the ideas above ☝️ 

### Possible implementation

You can get the navbar codes & ideas here 👉 https://tailwindui.com/components/marketing/page-examples/pricing-pages

Please center the OVERVIEW | DAO | Community | Help and the launch app should separate to the right 
![image](https://user-images.githubusercontent.com/73097560/141460445-2f71d51c-3d3d-4132-a44a-949fb7f004b7.png)

### Additional information

Please comment here if you want to work with this issue before making PR.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhinavMV** [comment]
Any suggestions for this design?
![image](https://user-images.githubusercontent.com/35369843/141672552-8e522a4b-b0e7-4163-9029-2180a047ba43.png)
![image](https://user-images.githubusercontent.com/35369843/141672573-00f3f800-fc84-43be-80b6-8681bc1c10f8.png)

**Comment by vinzvinci** [comment]
I think we can use that design, just remove so much white space in sub-navbar.

Hmm can u also remove that join now
![image](https://user-images.githubusercontent.com/73097560/141673379-d69746cb-7029-4773-96fe-cc6a6282524e.png)

**Comment by vinzvinci** [comment]
![image](https://user-images.githubusercontent.com/73097560/141673499-f27fd74b-0d11-4e43-90e5-abce71121b36.png)
 can u also add dropdown arrow

**Comment by AbhinavMV** [comment]
Removed spacing in subnavbar and added dropdown arrow.
![image](https://user-images.githubusercontent.com/35369843/141675640-995a18e6-64f4-494f-8ec8-2ba8100b4eb6.png)

Could you provide the links for the following to add them in subnavbar:
| Forum
| Builders Program
| FAQ
| Tutorials
| Documentation
| Code of Conduct

**Comment by vinzvinci** [comment]
https://community.devprotocol.xyz/ = https://community.devprotocol.xyz/
Documentation: https://docs.devprotocol.xyz/
Code of Conduct: https://github.com/dev-protocol/community/blob/main/CODE_OF_CONDUCT.md
Tutorials = https://initto.devprotocol.xyz/

FAQ and Builders Program will be available soon

**Comment by vinzvinci** [comment]
My mistake, 

there's duplicate in desktop view @AbhinavMV 
![image](https://user-images.githubusercontent.com/73097560/141680240-67744ce0-bf6e-4063-b61c-9a5ee43f79ae.png)

**Comment by AbhinavMV** [comment]
Sorry about that forgot to add one tailwind class.
Do i need to create a new PR now?

**Comment by vinzvinci** [comment]
> Sorry about that forgot to add one tailwind class. Do i need to create a new PR now?

yeah you can create one
