### ISSUE TITLE
[FEATURE] Set the navbar position fixed

### ISSUE THREAD

**Issue by ZaidKhan2002** [web3community/devprotocol.xyz#143]
### Problem subject

Navbar

### Description

Navbar is not sticky at top in any of the pages.

### Expected behavior/contents

Navbar should be sticky so that user can navigate using Navbar rather then scrolling up.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Would you like to work on this, @ZaidKhan2002? 🙂

**Comment by ZaidKhan2002** [comment]
Yes I would like to work on this.

**Comment by shuklaritvik06** [comment]
> Yes I would like to work on this.

Okay I am assigning you this issue, Here you go 🚀

**Comment by vinzvinci** [comment]
The issue was taken, please see the other issue that you like to work on. This issue has been fixed

**Comment by ZaidKhan2002** [comment]
I was about to make PR regarding this issue it's okay. I will se another issue.

**Comment by vinzvinci** [comment]
We currently need help in #131

**Comment by ZaidKhan2002** [comment]
Sure!!
