### ISSUE TITLE
[BUG] Image not showing properly in mobile view

### ISSUE THREAD

**Issue by AbhinavMV** [web3community/devprotocol.xyz#152]
### Problem subject

Other: Image orientation issue

### Description

Top of the image is cut off in mobile view For the following pages
Creators
Developers
Patrons
Screenshot:
![image](https://user-images.githubusercontent.com/35369843/142671853-cb13304e-baa0-4bac-934d-ea0eef6535f3.png)

### Expected behavior/contents

Full Image should be visible

### Actual behavior/contents

Image Cut off from top

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
> ### Problem subject
> Other: Image orientation issue
> 
> ### Description
> Top of the image is cut off in mobile view For the following pages Creators Developers Patrons Screenshot: ![image](https://user-images.githubusercontent.com/35369843/142671853-cb13304e-baa0-4bac-934d-ea0eef6535f3.png)
> 
> ### Expected behavior/contents
> Full Image should be visible
> 
> ### Actual behavior/contents
> Image Cut off from top
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Thanks for reporting that bug. Are u gonna take this issue?

**Comment by AbhinavMV** [comment]
Sure will fix it now 👍

**Comment by vinzvinci** [comment]
> Sure will fix it now 👍

Awesome, thank you 🎉
