### ISSUE TITLE
[FEATURE] Add FAQ page

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#153]
### Detailed description

Hey folks,

I'm proposing to add the FAQ page with 10 prepared questions and answer using Lorem ipsum 😄 Just don't link the FAQ in the navbar for now 

![image](https://user-images.githubusercontent.com/73097560/142673896-914ea01d-5b8f-4c5d-b117-d6e9223d4f70.png)

We are using TailwindUI and we have a subscription to it, so don't be bothered to use it on our site.

### Context

This will benefit us if there's already a template in our codebase, then we can be able to change the info. once the Q&A is ready

### Possible implementation

You can see the codes here: 
https://tailwindui.com/components/marketing/sections/faq-sections#component-8017f4faee579f7ca518cdde140d4689

### Additional information

Thank you ❤️ 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Count me in! Let me know if you need any help writing the questions. 🙂

**Comment by vinzvinci** [comment]
Sure @Panquesito7.

**Comment by krishguptadev** [comment]
Is this gonna be a new page or just a section to another?

**Comment by vinzvinci** [comment]
> Is this gonna be a new page or just a section to another?

New page, because it will be long. I think they are preparing 30 questions and answers.

**Comment by krishguptadev** [comment]
> > Is this gonna be a new page or just a section to another?
> 
> New page, because it will be long. I think they are preparing 30 questions and answers.

Ah I see. Waiting for someone to grab this in the next 12 hours, else assign me

**Comment by vinzvinci** [comment]
Sure @krishguptadev 🚀

**Comment by Panquesito7** [comment]
> > > Is this gonna be a new page or just a section to another?
> > 
> > 
> > New page, because it will be long. I think they are preparing 30 questions and answers.
> 
> Ah I see. Waiting for someone to grab this in the next 12 hours, else assign me

Maybe let's wait a week or a few days instead? 😅

**Comment by krishguptadev** [comment]
> > > > Is this gonna be a new page or just a section to another?
> > > 
> > > 
> > > New page, because it will be long. I think they are preparing 30 questions and answers.
> > 
> > 
> > Ah I see. Waiting for someone to grab this in the next 12 hours, else assign me
> 
> Maybe let's wait a week or a few days instead? 😅

Sure!

**Comment by vinzvinci** [comment]
This was open 2 days ago, how about let's wait until Wednesday?

**Comment by krishguptadev** [comment]
> This was open 2 days ago, how about let's wait until Wednesday?

Just ping me whenever you think 😄

**Comment by AbhinavMV** [comment]
if no one is working on this i can 😄

**Comment by vinzvinci** [comment]
I think u can take this issue @AbhinavMV, Krish is working on 2 issues and recently make PR and it's not done yet.

**Comment by vinzvinci** [comment]
Can u put english and japanese version @AbhinavMV? The FAQ has English and Japanese

**Comment by AbhinavMV** [comment]
I will try once and let you know.
Right now i will fill it with random data (Both english and japanese).
