### ISSUE TITLE
[FEATURE] Add Community Partners page

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#156]
### Detailed description

Another page for Dev Protocol community partners

here's the community partners 
![image](https://user-images.githubusercontent.com/73097560/142944002-4483a6ce-208a-432c-9260-300c6991ef5a.png)

### Context

This is one of the most important page in this website

### Possible implementation

I think better use cards for this, u can get some ideas here: https://tailwindui.com/components/application-ui/lists/grid-lists#component-5d72b187beb968e12db89fe49f272b18

### Additional information

Anyone can start working with this, hopefully will be done this week.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krishguptadev** [comment]
I would love to work it 😄

**Comment by vinzvinci** [comment]
> I would love to work it 😄

Sure, thanks 🎉

**Comment by krishguptadev** [comment]
I would like details for the partners to add them all 😄 

I need Name, Image URL, Description and Link, which will be compiled to

```js
   {
    'name': 'Web3Community',
    'image': 'https://github.com/Web3Community.png',
    'link': 'https://web3community.github.io',
    'description': 'An Open Source Community that focuses on decentralized applications, web 3, and blockchain technologies 🚀'
  }
  ```

**Comment by vinzvinci** [comment]
> I would like details for the partners to add them all 😄
> 
> I need Name, Image URL, Description and Link, which will be compiled to
> 
> ```js
>    {
>     'name': 'Web3Community',
>     'image': 'https://github.com/Web3Community.png',
>     'link': 'https://web3community.github.io',
>     'description': 'An Open Source Community that focuses on decentralized applications, web 3, and blockchain technologies 🚀'
>   }
> ```

Thanks, I will ask this to mayu

**Comment by vinzvinci** [comment]
Please add this:

Microsoft for Startups
https://devprotocol.xyz/assets/msstartups.png    
https://www.microsoft.com/ja-jp/biz/startups/default.aspx    

Description:
We provide entrepreneurs and founders of startups with the cloud resources and mentoring they need in their journey from idea to exit

**Comment by krishguptadev** [comment]
> Microsoft for Startups

Hmm, the logo doesn't fit for a circle. also, I need a logo for m-zomia. (a circular one)

**Comment by vinzvinci** [comment]
> > Microsoft for Startups
> 
> Hmm, the logo doesn't fit for a circle. also, I need a logo for m-zomia. (a circular one)

Please check team-web3 discord channel for m-zomia logo

I'm not good editor but I tried to edit the logo of Microsoft for Startups, will this work?
![msstartups](https://user-images.githubusercontent.com/73097560/143192555-92a62ed6-06f3-405c-94b1-99afe264fa31.png)

**Comment by krishguptadev** [comment]
> > > Microsoft for Startups
> > 
> > 
> > Hmm, the logo doesn't fit for a circle. also, I need a logo for m-zomia. (a circular one)
> 
> Please check team-web3 discord channel for m-zomia logo
> 
> I'm not good editor but I tried to edit the logo of Microsoft for Startups, will this work? ![msstartups](https://user-images.githubusercontent.com/73097560/143192555-92a62ed6-06f3-405c-94b1-99afe264fa31.png)

this is even worse 🙄

**Comment by vinzvinci** [comment]
> > > > Microsoft for Startups
> > > 
> > > 
> > > Hmm, the logo doesn't fit for a circle. also, I need a logo for m-zomia. (a circular one)
> > 
> > 
> > Please check team-web3 discord channel for m-zomia logo
> > I'm not good editor but I tried to edit the logo of Microsoft for Startups, will this work? ![msstartups](https://user-images.githubusercontent.com/73097560/143192555-92a62ed6-06f3-405c-94b1-99afe264fa31.png)
> 
> this is even worse 🙄

xD, please try to make solutions.

**Comment by AbhinavMV** [comment]
Maybe you can take just the rocket part for the logo and crop the text.
In current PR cards are used right. So the text will be will be displayed as title of the card. 
This can be done for other logos as well showing text in both title and logo seems redundant.

**Comment by yumemayu** [comment]
Can I add a new partnership information here? 🙂

```
- Name: experify
- Logo: https://u.pcloud.link/publink/show?code=kZBPgqXZNbE4G0Ch8ryAuMyJAFu19fsYa0KX I prefer the Moss Green Variant, but you can check if other color variants are better matching with DEV protocols colors
- Links: https://www.instagram.com/experify3dprint/ | https://www.facebook.com/Experify3DPrint
- About: A 3D printing and 3D scanning service placed in Plovdiv. We provide wide variety of services and materials: prototyping, cosplay props, educational projects, robotics, etc. 
```
