### ISSUE TITLE
[FEATURE] Add Testimonials in creator page

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#160]
### Detailed description

Hey folks! Another green square 🎉 

Let's add testimonials to the [creators](https://devprotocol.xyz/creators) page

### Context

This is very important to know the creators experience within the Dev Protocol

### Possible implementation

I suggest to use this
https://tailwindui.com/components/marketing/sections/testimonials#component-54ee9cbce13afa3082f12b00ff1c00a6
![image](https://user-images.githubusercontent.com/73097560/143171953-5cd73776-b21c-490f-b399-450713b23579.png)

### Additional information

Here's their testimonials:

### Sindre 
"I like how the Dev Protocol is improving open source sustainability in an innovative way"

link: https://twitter.com/sindresorhus

### μ-zomia
"DevProtocol is born out of the love of people supporting people. Once you understand that, there's no reason not to be part of the team."

link: https://twitter.com/zomia12

### HiDE
"DEV protocol is a sustainable source of funding for the community ecosystem that uses our services to operate.
It is a core feature of the HiÐΞ protocol and is a very important financial resource. As OSS creators, we feel free to use some DEV tokens for development and redistribute them in our services. I will continue to do my best for the further development of the DEV community that you have staked out for us."

link: https://twitter.com/HideProtocol

### ScytheSwap 
"Being a part of Dev Protocol has been an incredible experience. When I was on boarded to stakes.social I was exposed to an audience of OSS creators and enthusiasts alike who helped to fund our project while simultaneously engaging with us, creating long-term connections with some of the most intelligent developers in the world. Dev Protocol, and all that it offers to OSS contributors, along with its community are truly one of a kind."

link: https://github.com/ScytheSwapProtocol

### IslandviewDigital
"Being part of Dev Protocol not only means being able to sustainably raise capital for our immersive, revenue-generating VR real estate development projects, it means being part of a community of talented innovators with whom we can synergize to bring even more value to the protocol."

link: https://twitter.com/IslandVDigital

### Samuil / SQ-UI
"DEV protocol jump-started our project and helped us do what we love."

link: https://twitter.com/samuil4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
For anyone who's working or will work on this: I'd love to help in anything! 😄

**Comment by krishguptadev** [comment]
> For anyone who's working or will work on this: I'd love to help in anything! 😄

Hey! Made PR, #161. Please add your valuable reviews.
