### ISSUE TITLE
[OTHER] Add a new community partners 

### ISSUE THREAD

**Issue by yumemayu** [web3community/devprotocol.xyz#173]
### What would you like to share?

URL: https://github.com/intlify
Logo: https://github.com/intlify/art  
Description: Intlify is a project that aims to improve Developer Experience in software internationalization. We will aim to improve the Developer Experience of internationalization by providing libraries, frameworks, and tools that break down barriers to internationalization.

Can you choose a logo from the repository? ^

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
link: https://intlify.dev/ - I put their website

Panquesito7 suggested it and I think it's good.
