### ISSUE TITLE
[FEATURE] Divide the FAQ for each category

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#176]
### Detailed description

Divide the FAQ and put them in their category.

You will see the FAQ and categories here 👇 
https://docs.google.com/spreadsheets/d/1VyrRce4qvh2b6rNmbO4QmquQt0eN3_gsAoNhbxWU-jI/edit#gid=0

### Context

I think this makes the page clean, currently, the FAQ page is messed for me https://devprotocol.xyz/faq

### Possible implementation

Make something like this if possible 👉 https://rally.io/evergreen/faq 

or suggest  your ideas below

### Additional information

Thank you :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Simperfy** [comment]
Awesome, can I do this one?

**Comment by vinzvinci** [comment]
Yeah sure @Simperfy 🚀

**Comment by Simperfy** [comment]
Nice ❤️
