### ISSUE TITLE
[BUG] Navbar icons position changes in mobile view

### ISSUE THREAD

**Issue by AbhinavMV** [web3community/devprotocol.xyz#179]
### Problem subject

- [x] Other - UI

### Description

Toggle Button and Hamburger Button goes to next line in mobile view

Screenshot:
![image](https://user-images.githubusercontent.com/35369843/144469925-433b4ccc-c3be-4492-864f-7207bd4966d8.png)

### Expected behavior/contents

Icons should be placed at right side

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Simperfy** [comment]
Would like to work on this one.
