### ISSUE TITLE
[FEATURE] Reorder the Q&A

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#182]
### For Everyone
1. What is the Dev Protocol?
2. What is the mission and vision of Dev Protocol?
3. What is the way for buying DEV token?
4. What is a DEV token and what its benefits?
5. Where can I use my DEV token?
6. Where can I find the Dev Protocol roadmap?
7. Is the DEV token a security?

### For Creators
1. How can creators make money with Dev Protocol?
2. How to use stakes.social?
3. Can I only register OSS?
4. Can I register a project that is under development (not yet completed)?
5. Can I register a project that is raising funds?
6. How to promote my OSS project to get sponsor on stakes.social
7. Can Property Token's name be changed?
8. When can I withdraw my creators' fees? (Project Owner)
9. When can project team members withdraw their creator fees?
10. Can I stop using the Dev Protocol
11. What should I do if I want to stop the activity?
12. Are Property tokens securities? Are there any risks involved in issuing them?

### Context

We better reorder them, the information above 

### Possible implementation

...

### Additional information

https://devprotocol.xyz/faq

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Simperfy** [comment]
Can I do this?

**Comment by vinzvinci** [comment]
Yes yes @Simperfy
