### ISSUE TITLE
[FEATURE] Update & Add button to apply for community partners

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#187]
### Detailed description

Can this text move upward?

![image](https://user-images.githubusercontent.com/73097560/145012532-ec1a048f-5ed5-45ef-b24b-2e09d8ea4fab.png)

~~-~~
We will add a button for: **Become a community partner** 

I'm not sure if it will look good to put it in this section 
![image](https://user-images.githubusercontent.com/73097560/145013725-052088e9-a584-4cb4-8a25-580db8cdbf8c.png)

or it will look good in the bottom?

### Context

We discuss this before but as of now, no one working on this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Simperfy** [comment]
I think it will look better if it's move upwards.
![image](https://user-images.githubusercontent.com/28738855/145025050-651af30a-5e7e-41f6-80ec-36ad84e4b4f4.png)

So that it is consistent with the other page.
![image](https://user-images.githubusercontent.com/28738855/145025132-bcaf830e-a0fa-4ee6-b4e8-8bdcdf8684e5.png)

**Comment by vinzvinci** [comment]
> 

Hmm yeah, thanks. Would u like to take this issue?

**Comment by Panquesito7** [comment]
https://github.com/web3community/devprotocol.xyz/pull/188#discussion_r764227207

**Comment by AbhinavMV** [comment]
On the Community Partners page,
How about changing the card's background color to purple(in dark mode) and grey(in light mode), so all pages look similar?
Also in mobile, reduce left and right margin as well
Thoughts? 🤔 @web3community/core-maintainer

**Comment by krishguptadev** [comment]
Looks good to me.

**Comment by Simperfy** [comment]
> On the Community Partners page, How about changing the card's background color to purple(in dark mode) and grey(in light mode), so all pages look similar? Also in mobile, reduce left and right margin as well Thoughts? thinking @web3community/core-maintainer

I'll look into it.
