### ISSUE TITLE
[FEATURE] Add about page, transfer team section and include to overview 

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#189]
### Detailed description

# About

## What is the mission and vision of Dev Protocol

The mission of Dev Protocol is to maximize creativity for every creator in the world, using the power of Blockchain and Decentralized Financial mechanism to enable creators to capitalize on their projects and achieve financial success, regardless of the size of the project.

## Where does the Dev Protocol idea come from?

The idea does not come from Open Source Software (OSS) but traditional work. One of us, the founders, found out that Japanese artisans of temples and shrines were economically less valued despite their elaborate and long-lasting works. Then we got together and started to tackle continuous finance for creators in 2015. We established Dev Protocol in 2018 to begin implementing our sustainable supporting scheme by blockchain technology.

## The value of the Dev Protocol

The positive cycle created by Public goods such as OSS begins sustainability and enables more OSS developers, artists, researchers, and other creators to live independently. To collaborate with more projects freely is the greatest value for all. 

The core features of Dev Protocol are evaluation, distribution and management for the creator's projects. By using Dev Protocol, even a small, newly started project can increase its evaluation and improve its market capitalization. The ability to achieve this has been limited to stock companies now, but Dev Protocol is opening up that possibility to all creators.

The first step for creators is to prove their ownership of the project and issue their own property tokens(ERC-20). Once issue tokens, creators can monetize through staking by supporters, share and divide them with their co-developers. In addition, these tokens allow creators to give partial ownership for all the contributors involved in the OSS development in order to provide a sustainable opportunity for profit without the need of token sales. 

This is just a description of the basic components of the Dev Protocol ecosystem. There are many possible use cases for this new economic infrastructure designed for creators, so please try it out for yourself!

## The Team
![image](https://user-images.githubusercontent.com/73097560/145155218-9052b9bd-108a-4aa7-87ec-7d4ad93278f9.png)

### Context

This is also important part of our website, best to include in overview nav-item

### Possible implementation

Add about page, the information above ☝️ and remove the question & answer in [FAQ](https://devprotocol.xyz/faq)
![image](https://user-images.githubusercontent.com/73097560/145154876-b5c90b00-fbd2-41f8-9384-1c4a7d2e641b.png)

Remove the team section in [developers](https://devprotocol.xyz/developers) page then transfer it to about page

### Additional information

Thank you :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhinavMV** [comment]
i can work on this 😄
(if no one is already working on this)

**Comment by vinzvinci** [comment]
Feel free to work on this issue @AbhinavMV
