### ISSUE TITLE
[FEATURE] Add community partners form

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#194]
### Detailed description

This was discuss on this PR https://github.com/web3community/devprotocol.xyz/pull/188#discussion_r765469316

Use this: https://tailwindui.com/components/marketing/sections/contact-sections#component-dec976a631662b509173ba8b848c49cd

### Context

It will allow our future partners to apply easily

### Possible implementation

The fields information will be

Founder Name
Community Name
Website
Email
Why do you want to be partner with us?
How did you hear about us?

Add radio button for Agreement to terms of use and code of conduct.

![image](https://user-images.githubusercontent.com/73097560/145966023-ae75b72c-b0e5-4504-bd81-2fbe96f43ee6.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Should we ask if they have a Discord community/user, as well as their invitation link?

**Comment by vinzvinci** [comment]
> Should we ask if they have a Discord community/user, as well as their invitation link?

No, it should be on their website.

**Comment by Simperfy** [comment]
After submitting the form, where are we going to save the data?

**Comment by vinzvinci** [comment]
> After submitting the form, where are we going to save the data?

Hmm airtable or google sheets 🤔

**Comment by Simperfy** [comment]
If we are going to store it in google sheets, who is going to provide the google sheets API key?

**Comment by vinzvinci** [comment]
I can provide @Simperfy

**Comment by Simperfy** [comment]
If that's the case I can work on this one.

**Comment by Simperfy** [comment]
@vinzvinci  What will be the values in this section?

![image](https://user-images.githubusercontent.com/28738855/146649667-3ba71816-284b-4d79-b9ea-96f67ca45dd7.png)

**Comment by vinzvinci** [comment]
remove the number, we don't have any telephone number :D 

Hmm about the text below contact:

For more information, please reach out to our support team.
