### ISSUE TITLE
[FEATURE] Complete the footer section

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#24]
### Detailed description

https://www.figma.com/file/rmCKKIsjSWCH0q6lObDQC8/Dev-Protocol-design?node-id=0%3A1

### Context

Can someone work with this? You can look at the figma

![image](https://user-images.githubusercontent.com/73097560/136314739-55b7df55-bfe1-421a-8589-5c7535c6d4ff.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krishguptadev** [comment]
@vinzvinci The could you also share the links of the social media platforms here

**Comment by Himanshu664** [comment]
@vinzvinci I want to work please assign

**Comment by krishguptadev** [comment]
> Does someone delete the comment?
> 
> > @vinzvinci The could you also share the links of the social media platforms here
> 
> http://devprotocol.xyz/ you can see it here (footer section)

afaik Looks like the assignee has unassigned them and decided to not work on this issue (they deleted the comment too). but np, I can be always assigned if the issue is on hold from a while

**Comment by rizastoday** [comment]
can i get link for social medias ?
