### ISSUE TITLE
[FEATURE] Build the dynamic medium blog post section

### ISSUE THREAD

**Issue by krishguptadev** [web3community/devprotocol.xyz#29]
### Detailed description

Write code that fetches all the blog posts by devprotocol on medium, Then converts it into markup styled with Tailwind CSS

To be implemented in [vue](https://vuejs.org) or [astro](https://astro.build)

Styling to be done with [Tailwind CSS](https://tailwindcss.com)

Dev Protocol Medium: https://medium.com/devprtcl

RSS Feed: https://medium.com/feed/devprtcl

Design to be achieved:

![Blog Post Design. Dev Protocol Website 2.0](https://user-images.githubusercontent.com/91655303/136349111-7b04d8b8-4bd0-45b4-9aa8-b22be0ab9f9f.png)

Design File available at [figma](https://www.figma.com/file/nEEhTw6azAwS6fgJ21j8lL/Dev-Protocol-design-(Copy)?node-id=1%3A135)

For more information/support/opportunities to contribute join our [discord server](https://discord.gg/2S8PNMRQkq)

### Context

To be implemented at: https://github.com/web3community/devprotocol.xyz/blob/main/src/pages/index.astro#L70-L76

Discussed on [Discord](https://discord.gg/2S8PNMRQkq)

### Possible implementation

Use this API: https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/devprtcl

Fetch it using: https://docs.astro.build/guides/data-fetching#fetch

If you are familiar to jsx, here is how to repeat the array into generating blog posts: https://docs.astro.build/core-concepts/astro-components#comparing-astro-versus-jsx

This is a example of somewhat how you have to build it:

```html
---
const blogs = (await (await Astro.fetch('https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/devprtcl')).json())

// Let's assume the response were to be [{ title: 'Blog Post' }, img: '<img_url>'}, { title: 'Blog Post' }, img: '<img_url>'}]
---

<ul>
{blogs.map(blog => <li><img src="{blog.img}"><h4>{blog.title}</h4></li>)}
</ul>
```

Also use tailwindcss classes to style the components.

**Note: This is just example markup, please use more structured and semantic markup. The response also might not be the one displayed since it was just for a example.**

### Additional information

Discussed on Discord with @mkubdev. Credits to them for the rss-parsing API idea

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
any update with this?

**Comment by Sukriti-sood** [comment]
@vinzvinci Sorry, Still no updates. Will update you soon.
