### ISSUE TITLE
[BUG] Footer looks far different from design

### ISSUE THREAD

**Issue by gptkrsh** [web3community/devprotocol.xyz#40]
### Description

Footer doesn't follow the design schema

### Expected behavior

-

### Actual behavior

-

### Possible fix

-

### Steps to reproduce

-

### Context

-

### Additional information

Was introduced in #39 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Next time, please provide more information about the bug, so other maintainers and people can help. 🙂

**Comment by vinzvinci** [comment]
The owner of the Dev Protocol wants this :) they are also in our community ^^

![image](https://user-images.githubusercontent.com/73097560/136658748-486918cb-6f00-4ca8-9750-73ef003a1bea.png)

**Comment by krishguptadev** [comment]
> The owner of the Dev Protocol wants this :) they are also in our community ^^
> 
> ![image](https://user-images.githubusercontent.com/73097560/136658748-486918cb-6f00-4ca8-9750-73ef003a1bea.png)

Can I get the design file?

**Comment by 0rGaan1c** [comment]
Can I work on this?
