### ISSUE TITLE
[FEATURE] Add Dapps section

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#47]
### Detailed description

Link: https://www.figma.com/file/rmCKKIsjSWCH0q6lObDQC8/Dev-Protocol-design?node-id=0%3A1

![image](https://user-images.githubusercontent.com/73097560/136642169-cd6199e5-d921-4888-aa95-f08ff1dc6f69.png)

Please remove this
![image](https://user-images.githubusercontent.com/73097560/136642188-e86e83f5-a040-42ef-8b33-695bd2da2b13.png)

### Context

The changes made by the owner of Dev Protocol

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
These are the future application, just build static. here's the design https://www.figma.com/file/rmCKKIsjSWCH0q6lObDQC8/Dev-Protocol-design?node-id=0%3A1

**Comment by vinzvinci** [comment]
🆙

**Comment by vinzvinci** [comment]
This issue is open again

**Comment by Intelligent-Mosiac** [comment]
@krishguptadev  You can take it up.
