### ISSUE TITLE
[FEATURE] Improve the slider section

### ISSUE THREAD

**Issue by vinzvinci** [web3community/devprotocol.xyz#63]
### Detailed description

Krish is suggesting improve the slider section 

### Context

![image](https://user-images.githubusercontent.com/73097560/137087460-0b5a69e8-d52c-4630-bc65-2ce631fc9f89.png)
 +
reduce the white space in mobile and tablet view
![image](https://user-images.githubusercontent.com/73097560/137065114-d07de2c1-4ff0-46c8-a8a9-0f4bdd17926a.png)
+
try to adopt the alignment of logo
![image](https://user-images.githubusercontent.com/73097560/137075384-dc9debd0-ec5b-49a5-bbf3-0ecc17113723.png)

### Possible implementation

Figma link: https://www.figma.com/file/rmCKKIsjSWCH0q6lObDQC8/Dev-Protocol-design?node-id=0%3A1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krishguptadev** [comment]
On another note I think we do not need that fade animation the counter would be enough

**Comment by vinzvinci** [comment]
> On another note I think we do not need that fade animation the counter would be enough

thanks, I updated the screenshot above ☝️

**Comment by vinzvinci** [comment]
yes @the-veshh

**Comment by krishguptadev** [comment]
@the-veshh just a slight reminder, PRs merged/approved after 12am GMT-12 would not be counted for Hacktoberfest 🙂

**Comment by vinzvinci** [comment]
No updates from @the-veshh 😢, will unassigned this and maybe someone can take the issue

**Comment by ZaidKhan2002** [comment]
I would like to work on this issue

**Comment by vinzvinci** [comment]
Sure, please do @ZaidKhan2002

**Comment by ZaidKhan2002** [comment]
<img width="1183" alt="Screenshot 2021-11-11 at 12 15 49 PM" src="https://user-images.githubusercontent.com/71960989/141251060-620a9042-5eaf-457b-8c15-4ec12bddf8eb.png">

@vinzvinci is it ok ??

**Comment by vinzvinci** [comment]
Yeah looks good @ZaidKhan2002

**Comment by ZaidKhan2002** [comment]
I tried to add some more padding-top but tailwind has some pre-defined padding size

**Comment by vinzvinci** [comment]
Well, it looks good. Thanks for making PR @ZaidKhan2002
