### ISSUE TITLE
[BUG] The backed by section behaves weiredly when passing through navbar

### ISSUE THREAD

**Issue by SyedFasiuddin** [web3community/devprotocol.xyz#67]
### Description

When we scroll and get to the backed by section, it appears to be merged with the nav bar

### Expected behavior

It should just go beneath the navbar

### Actual behavior

It appears as if it is merging with the navbar

### Steps to reproduce

Just scroll through the "backed by" section

### Context

It will effect the the people visiting the website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Cool cool, thanks for raising this issue

**Comment by SyedFasiuddin** [comment]
I would have done this btw
