### ISSUE TITLE
[FEATURE] Add a dark mode to the website

### ISSUE THREAD

**Issue by Panquesito7** [web3community/devprotocol.xyz#87]
### Detailed description

I think a dark mode should be added to the website. I currently use Dark Reader to make the websites dark, but for Dev Protocol, it doesn't look that good, IMO.

![image](https://user-images.githubusercontent.com/51391473/139296856-9f99fe7b-2c1d-4051-9464-286565885340.png)

### Context

Many users do not like the light mode, they prefer dark mode (like me 😂), so I think it'd be a good idea to add a dark mode to the website.

### Possible implementation

Add a dark mode to the website, that can be toggled with a button in the navbar.

### Additional information

Nope.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhinavMV** [comment]
I have made some changes in figma file for this.
How does this look ? -> https://www.figma.com/file/xlEJolc6UbPl4uGwMV8XFt/Dev-Protocol-design-(Copy)?node-id=0%3A1

**Comment by krishguptadev** [comment]
> I have made some changes in figma file for this. How does this look ? -> https://www.figma.com/file/xlEJolc6UbPl4uGwMV8XFt/Dev-Protocol-design-(Copy)?node-id=0%3A1

Let's just wait for @aggre's response before working on anything related to this 🙂

**Comment by shuklaritvik06** [comment]
> > I have made some changes in figma file for this. How does this look ? -> https://www.figma.com/file/xlEJolc6UbPl4uGwMV8XFt/Dev-Protocol-design-(Copy)?node-id=0%3A1
> 
> Let's just wait for @aggre's response before working on anything related to this 🙂 

Yes we should wait for his response :) as Vinz also commented above

**Comment by AbhinavMV** [comment]
> > > I have made some changes in figma file for this. How does this look ? -> https://www.figma.com/file/xlEJolc6UbPl4uGwMV8XFt/Dev-Protocol-design-(Copy)?node-id=0%3A1
> > 
> > 
> > Let's just wait for @aggre's response before working on anything related to this 🙂
> 
> Yes we should wait for his response :) as Vinz also commented above

Sure 👍 
(Never used figma before so was trying to understand it by doing something useful 😄)

**Comment by shuklaritvik06** [comment]
> > > > I have made some changes in figma file for this. How does this look ? -> https://www.figma.com/file/xlEJolc6UbPl4uGwMV8XFt/Dev-Protocol-design-(Copy)?node-id=0%3A1
> > > 
> > > 
> > > Let's just wait for @aggre's response before working on anything related to this slightly_smiling_face
> > 
> > 
> > Yes we should wait for his response :) as Vinz also commented above
> 
> Sure +1 (Never used figma before so was trying to understand it by doing something useful smile)

Great! Thanks for suggesting the changes! We appreciate it :)

**Comment by vinzvinci** [comment]
I will mention aggre again

**Comment by vinzvinci** [comment]
Okay let's go for the dark mode @AbhinavMV, they like to have it

**Comment by aggre** [comment]
Thanks for the ping! I was receiving notifications from GitHub, but couldn't respond, sorry!

By the way, I agree with the dark mode! In addition, dynamic colors using media queries and custom properties also would be very nice.

**Comment by vinzvinci** [comment]
Okay, want to be assign to this @AbhinavMV?

**Comment by AbhinavMV** [comment]
sure @vinzvinci will give it a try.
Might need some help.

**Comment by vinzvinci** [comment]
Raise PR so we can see the changes and let's see if we can suggest @AbhinavMV.

**Comment by vinzvinci** [comment]
We have current issues, please see the 3 pages in **overview**, the dark mode there is not quite good.

**Comment by vinzvinci** [comment]
CC @AbhinavMV

**Comment by AbhinavMV** [comment]
is

> We have current issues, please see the 3 pages in **overview**, the dark mode there is not quite good.

is the dark mode deployed on the official website? 🤔
i am not able to see it.

**Comment by vinzvinci** [comment]
Check: https://devprotocol.netlify.app/

**Comment by AbhinavMV** [comment]
> Check: https://devprotocol.netlify.app/ @AbhinavMV

will fix it and raise a PR.
(i did not expect the earlier PR to be merged this soon. i was waiting for more suggestions.)

**Comment by AbhinavMV** [comment]
![image](https://user-images.githubusercontent.com/35369843/142424042-4623aa79-e4c6-4ac2-8e40-b1ef097fc2db.png)
Just found out that devprotocol docs uses this color for dark mode
@vinzvinci  Do you want me to use this for background color? (For consistency across websites)

**Comment by vinzvinci** [comment]
> ![image](https://user-images.githubusercontent.com/35369843/142424042-4623aa79-e4c6-4ac2-8e40-b1ef097fc2db.png) Just found out that devprotocol docs uses this color for dark mode @vinzvinci Do you want me to use this for background color? (For consistency across websites)

Hmm, I'm not sure if it will look good on this website 🤔 What do u folks think @Panquesito7 @shuklaritvik06 @krishguptadev

**Comment by krishguptadev** [comment]
> > ![image](https://user-images.githubusercontent.com/35369843/142424042-4623aa79-e4c6-4ac2-8e40-b1ef097fc2db.png) Just found out that devprotocol docs uses this color for dark mode @vinzvinci Do you want me to use this for background color? (For consistency across websites)
> 
> Hmm, I'm not sure if it will look good on this website 🤔 What do u folks think @Panquesito7 @shuklaritvik06 @krishguptadev

it would be nice to use the same theme! 😄

**Comment by vinzvinci** [comment]
Does the theme fit the website @AbhinavMV? If yeah, let's use the same theme

**Comment by shuklaritvik06** [comment]
> > > ![image](https://user-images.githubusercontent.com/35369843/142424042-4623aa79-e4c6-4ac2-8e40-b1ef097fc2db.png) Just found out that devprotocol docs uses this color for dark mode @vinzvinci Do you want me to use this for background color? (For consistency across websites)
> > 
> > Hmm, I'm not sure if it will look good on this website 🤔 What do u folks think @Panquesito7 @shuklaritvik06 @krishguptadev
> 
> it would be nice to use the same theme! 😄 

Hmm true 😄
